// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apm-dev/evm-tx-sender/internal/domain (interfaces: Signer)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_signer.go -package=mocks github.com/apm-dev/evm-tx-sender/internal/domain Signer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSigner is a mock of Signer interface.
type MockSigner struct {
	ctrl     *gomock.Controller
	recorder *MockSignerMockRecorder
	isgomock struct{}
}

// MockSignerMockRecorder is the mock recorder for MockSigner.
type MockSignerMockRecorder struct {
	mock *MockSigner
}

// NewMockSigner creates a new mock instance.
func NewMockSigner(ctrl *gomock.Controller) *MockSigner {
	mock := &MockSigner{ctrl: ctrl}
	mock.recorder = &MockSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSigner) EXPECT() *MockSignerMockRecorder {
	return m.recorder
}

// Addresses mocks base method.
func (m *MockSigner) Addresses() []common.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Addresses")
	ret0, _ := ret[0].([]common.Address)
	return ret0
}

// Addresses indicates an expected call of Addresses.
func (mr *MockSignerMockRecorder) Addresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Addresses", reflect.TypeOf((*MockSigner)(nil).Addresses))
}

// HasAddress mocks base method.
func (m *MockSigner) HasAddress(addr common.Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAddress", addr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasAddress indicates an expected call of HasAddress.
func (mr *MockSignerMockRecorder) HasAddress(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAddress", reflect.TypeOf((*MockSigner)(nil).HasAddress), addr)
}

// Sign mocks base method.
func (m *MockSigner) Sign(ctx context.Context, sender common.Address, tx *types.Transaction, chainID *big.Int) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", ctx, sender, tx, chainID)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockSignerMockRecorder) Sign(ctx, sender, tx, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockSigner)(nil).Sign), ctx, sender, tx, chainID)
}
