// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apm-dev/evm-tx-sender/internal/domain (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_repository.go -package=mocks github.com/apm-dev/evm-tx-sender/internal/domain Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	domain "github.com/apm-dev/evm-tx-sender/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ClaimNextQueued mocks base method.
func (m *MockRepository) ClaimNextQueued(ctx context.Context, sender string, chainID uint64, claimedBy string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNextQueued", ctx, sender, chainID, claimedBy)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNextQueued indicates an expected call of ClaimNextQueued.
func (mr *MockRepositoryMockRecorder) ClaimNextQueued(ctx, sender, chainID, claimedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNextQueued", reflect.TypeOf((*MockRepository)(nil).ClaimNextQueued), ctx, sender, chainID, claimedBy)
}

// CountQueuedTransactions mocks base method.
func (m *MockRepository) CountQueuedTransactions(ctx context.Context, sender string, chainID uint64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountQueuedTransactions", ctx, sender, chainID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountQueuedTransactions indicates an expected call of CountQueuedTransactions.
func (mr *MockRepositoryMockRecorder) CountQueuedTransactions(ctx, sender, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountQueuedTransactions", reflect.TypeOf((*MockRepository)(nil).CountQueuedTransactions), ctx, sender, chainID)
}

// CreateAttempt mocks base method.
func (m *MockRepository) CreateAttempt(ctx context.Context, attempt *domain.TxAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttempt", ctx, attempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttempt indicates an expected call of CreateAttempt.
func (mr *MockRepositoryMockRecorder) CreateAttempt(ctx, attempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttempt", reflect.TypeOf((*MockRepository)(nil).CreateAttempt), ctx, attempt)
}

// CreateTransaction mocks base method.
func (m *MockRepository) CreateTransaction(ctx context.Context, tx *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockRepositoryMockRecorder) CreateTransaction(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockRepository)(nil).CreateTransaction), ctx, tx)
}

// GetAttemptsByTransactionID mocks base method.
func (m *MockRepository) GetAttemptsByTransactionID(ctx context.Context, txID string) ([]*domain.TxAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttemptsByTransactionID", ctx, txID)
	ret0, _ := ret[0].([]*domain.TxAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttemptsByTransactionID indicates an expected call of GetAttemptsByTransactionID.
func (mr *MockRepositoryMockRecorder) GetAttemptsByTransactionID(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttemptsByTransactionID", reflect.TypeOf((*MockRepository)(nil).GetAttemptsByTransactionID), ctx, txID)
}

// GetBroadcastAttemptsByChain mocks base method.
func (m *MockRepository) GetBroadcastAttemptsByChain(ctx context.Context, chainID uint64) ([]*domain.TxAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBroadcastAttemptsByChain", ctx, chainID)
	ret0, _ := ret[0].([]*domain.TxAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBroadcastAttemptsByChain indicates an expected call of GetBroadcastAttemptsByChain.
func (mr *MockRepositoryMockRecorder) GetBroadcastAttemptsByChain(ctx, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBroadcastAttemptsByChain", reflect.TypeOf((*MockRepository)(nil).GetBroadcastAttemptsByChain), ctx, chainID)
}

// GetNonceCursor mocks base method.
func (m *MockRepository) GetNonceCursor(ctx context.Context, sender string, chainID uint64) (*domain.NonceCursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonceCursor", ctx, sender, chainID)
	ret0, _ := ret[0].(*domain.NonceCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNonceCursor indicates an expected call of GetNonceCursor.
func (mr *MockRepositoryMockRecorder) GetNonceCursor(ctx, sender, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonceCursor", reflect.TypeOf((*MockRepository)(nil).GetNonceCursor), ctx, sender, chainID)
}

// GetStuckTransactions mocks base method.
func (m *MockRepository) GetStuckTransactions(ctx context.Context, chainID uint64, olderThan big.Int) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStuckTransactions", ctx, chainID, olderThan)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStuckTransactions indicates an expected call of GetStuckTransactions.
func (mr *MockRepositoryMockRecorder) GetStuckTransactions(ctx, chainID, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStuckTransactions", reflect.TypeOf((*MockRepository)(nil).GetStuckTransactions), ctx, chainID, olderThan)
}

// GetSubmittedTransactions mocks base method.
func (m *MockRepository) GetSubmittedTransactions(ctx context.Context, chainID uint64) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmittedTransactions", ctx, chainID)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmittedTransactions indicates an expected call of GetSubmittedTransactions.
func (mr *MockRepositoryMockRecorder) GetSubmittedTransactions(ctx, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmittedTransactions", reflect.TypeOf((*MockRepository)(nil).GetSubmittedTransactions), ctx, chainID)
}

// GetTransaction mocks base method.
func (m *MockRepository) GetTransaction(ctx context.Context, id string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, id)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockRepositoryMockRecorder) GetTransaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockRepository)(nil).GetTransaction), ctx, id)
}

// GetTransactionByIdempotencyKey mocks base method.
func (m *MockRepository) GetTransactionByIdempotencyKey(ctx context.Context, key string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByIdempotencyKey indicates an expected call of GetTransactionByIdempotencyKey.
func (mr *MockRepositoryMockRecorder) GetTransactionByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByIdempotencyKey", reflect.TypeOf((*MockRepository)(nil).GetTransactionByIdempotencyKey), ctx, key)
}

// IncrementNonceCursor mocks base method.
func (m *MockRepository) IncrementNonceCursor(ctx context.Context, sender string, chainID uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementNonceCursor", ctx, sender, chainID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementNonceCursor indicates an expected call of IncrementNonceCursor.
func (mr *MockRepositoryMockRecorder) IncrementNonceCursor(ctx, sender, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementNonceCursor", reflect.TypeOf((*MockRepository)(nil).IncrementNonceCursor), ctx, sender, chainID)
}

// InitNonceCursor mocks base method.
func (m *MockRepository) InitNonceCursor(ctx context.Context, sender string, chainID, nonce uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitNonceCursor", ctx, sender, chainID, nonce)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitNonceCursor indicates an expected call of InitNonceCursor.
func (mr *MockRepositoryMockRecorder) InitNonceCursor(ctx, sender, chainID, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitNonceCursor", reflect.TypeOf((*MockRepository)(nil).InitNonceCursor), ctx, sender, chainID, nonce)
}

// ListTransactions mocks base method.
func (m *MockRepository) ListTransactions(ctx context.Context, filter domain.TxFilter) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, filter)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockRepositoryMockRecorder) ListTransactions(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockRepository)(nil).ListTransactions), ctx, filter)
}

// LogStateTransition mocks base method.
func (m *MockRepository) LogStateTransition(ctx context.Context, log *domain.TxStateLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogStateTransition", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogStateTransition indicates an expected call of LogStateTransition.
func (mr *MockRepositoryMockRecorder) LogStateTransition(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogStateTransition", reflect.TypeOf((*MockRepository)(nil).LogStateTransition), ctx, log)
}

// MarkAttemptStatus mocks base method.
func (m *MockRepository) MarkAttemptStatus(ctx context.Context, attemptID string, status domain.AttemptStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAttemptStatus", ctx, attemptID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAttemptStatus indicates an expected call of MarkAttemptStatus.
func (mr *MockRepositoryMockRecorder) MarkAttemptStatus(ctx, attemptID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAttemptStatus", reflect.TypeOf((*MockRepository)(nil).MarkAttemptStatus), ctx, attemptID, status)
}

// MarkConfirmed mocks base method.
func (m *MockRepository) MarkConfirmed(ctx context.Context, id string, receipt *domain.TxReceipt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkConfirmed", ctx, id, receipt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkConfirmed indicates an expected call of MarkConfirmed.
func (mr *MockRepositoryMockRecorder) MarkConfirmed(ctx, id, receipt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkConfirmed", reflect.TypeOf((*MockRepository)(nil).MarkConfirmed), ctx, id, receipt)
}

// MarkFailed mocks base method.
func (m *MockRepository) MarkFailed(ctx context.Context, id string, errCode domain.ErrorCode, errReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, errCode, errReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockRepositoryMockRecorder) MarkFailed(ctx, id, errCode, errReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockRepository)(nil).MarkFailed), ctx, id, errCode, errReason)
}

// MarkPending mocks base method.
func (m *MockRepository) MarkPending(ctx context.Context, id string, nonce uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPending", ctx, id, nonce)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPending indicates an expected call of MarkPending.
func (mr *MockRepositoryMockRecorder) MarkPending(ctx, id, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPending", reflect.TypeOf((*MockRepository)(nil).MarkPending), ctx, id, nonce)
}

// MarkReverted mocks base method.
func (m *MockRepository) MarkReverted(ctx context.Context, id string, receipt *domain.TxReceipt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReverted", ctx, id, receipt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkReverted indicates an expected call of MarkReverted.
func (mr *MockRepositoryMockRecorder) MarkReverted(ctx, id, receipt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReverted", reflect.TypeOf((*MockRepository)(nil).MarkReverted), ctx, id, receipt)
}

// MarkSubmitted mocks base method.
func (m *MockRepository) MarkSubmitted(ctx context.Context, id, txHash string, submittedAt *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSubmitted", ctx, id, txHash, submittedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSubmitted indicates an expected call of MarkSubmitted.
func (mr *MockRepositoryMockRecorder) MarkSubmitted(ctx, id, txHash, submittedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSubmitted", reflect.TypeOf((*MockRepository)(nil).MarkSubmitted), ctx, id, txHash, submittedAt)
}

// Migrate mocks base method.
func (m *MockRepository) Migrate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockRepositoryMockRecorder) Migrate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockRepository)(nil).Migrate), ctx)
}

// ResetPendingToQueued mocks base method.
func (m *MockRepository) ResetPendingToQueued(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPendingToQueued", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetPendingToQueued indicates an expected call of ResetPendingToQueued.
func (mr *MockRepositoryMockRecorder) ResetPendingToQueued(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPendingToQueued", reflect.TypeOf((*MockRepository)(nil).ResetPendingToQueued), ctx)
}

// SetNonceCursor mocks base method.
func (m *MockRepository) SetNonceCursor(ctx context.Context, sender string, chainID, nonce uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNonceCursor", ctx, sender, chainID, nonce)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNonceCursor indicates an expected call of SetNonceCursor.
func (mr *MockRepositoryMockRecorder) SetNonceCursor(ctx, sender, chainID, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNonceCursor", reflect.TypeOf((*MockRepository)(nil).SetNonceCursor), ctx, sender, chainID, nonce)
}
